### ISSUE TITLE
gpt模型 gpu 训练shard_stage3 + mp 出现bug

### ISSUE THREAD

**Issue by raining-dark** [PaddlePaddle/PaddleFleetX#1102]

**Comment by raining-dark** [comment]
报错信息：
Traceback (most recent call last):
File "tools/train.py", line 74, in
engine.fit(train_data_loader=train_data_loader,
File "/mnt/qiaohan/PaddleFleetX-develop/ppfleetx/core/engine/eager_engine.py", line 445, in fit
self._train_one_epoch(epoch_index, train_data_loader,
File "/mnt/qiaohan/PaddleFleetX-develop/ppfleetx/core/engine/eager_engine.py", line 351, in _train_one_epoch
loss = self._fit_impl(batch)
File "/mnt/qiaohan/PaddleFleetX-develop/ppfleetx/core/engine/eager_engine.py", line 519, in _fit_impl
self._optim_update_params()
File "/mnt/qiaohan/PaddleFleetX-develop/ppfleetx/core/engine/eager_engine.py", line 575, in _optim_update_params
self._scaler.step(self._optimizer)
File "/data/application/zhangtj/anaconda3/envs/paddle_gpt2/lib/python3.8/site-packages/paddle/amp/grad_scaler.py", line 757, in step
self._unscale(optimizer)
File "/data/application/zhangtj/anaconda3/envs/paddle_gpt2/lib/python3.8/site-packages/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_utils.py", line 235, in unscale_method
optimizer.update_slice()
File "/data/application/zhangtj/anaconda3/envs/paddle_gpt2/lib/python3.8/site-packages/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_stage3.py", line 277, in _update_params_slice
update_list = self._update_params()
File "/data/application/zhangtj/anaconda3/envs/paddle_gpt2/lib/python3.8/site-packages/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_stage3.py", line 598, in _update_params
param.fw_storage = _TensorWrapper(param)
File "/data/application/zhangtj/anaconda3/envs/paddle_gpt2/lib/python3.8/site-packages/paddle/distributed/fleet/meta_parallel/sharding/group_sharded_stage3.py", line 1086, in _TensorWrapper
shape=var.shape, dtype=var.dtype, name="slice@" + param.name
AttributeError: 'NoneType' object has no attribute 'shape'

参数配置，mp=2+shard degree=2（stage3），模型gpt345M
[2023-09-13 01:04:42,843] [INFO] - Data :
[2023-09-13 01:04:42,843] [INFO] - Eval :
[2023-09-13 01:04:42,843] [INFO] - dataset :
[2023-09-13 01:04:42,844] [INFO] - input_dir : /mnt/qiaohan/large_training_data
[2023-09-13 01:04:42,844] [INFO] - max_seq_len : 1024
[2023-09-13 01:04:42,844] [INFO] - mode : Eval
[2023-09-13 01:04:42,844] [INFO] - model_type : GPT
[2023-09-13 01:04:42,844] [INFO] - name : GPTDataset
[2023-09-13 01:04:42,844] [INFO] - num_samples : 240
[2023-09-13 01:04:42,844] [INFO] - seed : 1024
[2023-09-13 01:04:42,844] [INFO] - split : [969, 30, 1]
[2023-09-13 01:04:42,844] [INFO] - loader :
[2023-09-13 01:04:42,844] [INFO] - collate_fn : gpt_collate_fn
[2023-09-13 01:04:42,844] [INFO] - num_workers : 1
[2023-09-13 01:04:42,844] [INFO] - return_list : False
[2023-09-13 01:04:42,844] [INFO] - sampler :
[2023-09-13 01:04:42,844] [INFO] - batch_size : 4
[2023-09-13 01:04:42,844] [INFO] - drop_last : True
[2023-09-13 01:04:42,844] [INFO] - name : GPTBatchSampler
[2023-09-13 01:04:42,844] [INFO] - shuffle : False
[2023-09-13 01:04:42,844] [INFO] - Train :
[2023-09-13 01:04:42,844] [INFO] - dataset :
[2023-09-13 01:04:42,844] [INFO] - input_dir : /mnt/qiaohan/large_training_data
[2023-09-13 01:04:42,844] [INFO] - max_seq_len : 1024
[2023-09-13 01:04:42,844] [INFO] - mode : Train
[2023-09-13 01:04:42,844] [INFO] - model_type : GPT
[2023-09-13 01:04:42,845] [INFO] - name : GPTDataset
[2023-09-13 01:04:42,845] [INFO] - num_samples : 80000
[2023-09-13 01:04:42,845] [INFO] - seed : 1024
[2023-09-13 01:04:42,845] [INFO] - split : [969, 30, 1]
[2023-09-13 01:04:42,845] [INFO] - loader :
[2023-09-13 01:04:42,845] [INFO] - collate_fn : gpt_collate_fn
[2023-09-13 01:04:42,845] [INFO] - num_workers : 1
[2023-09-13 01:04:42,845] [INFO] - return_list : False
[2023-09-13 01:04:42,845] [INFO] - sampler :
[2023-09-13 01:04:42,845] [INFO] - batch_size : 4
[2023-09-13 01:04:42,845] [INFO] - drop_last : True
[2023-09-13 01:04:42,845] [INFO] - name : GPTBatchSampler
[2023-09-13 01:04:42,845] [INFO] - shuffle : False
[2023-09-13 01:04:42,845] [INFO] - Distributed :
[2023-09-13 01:04:42,845] [INFO] - dp_degree : 1
[2023-09-13 01:04:42,845] [INFO] - fuse_sequence_parallel_allreduce : False
[2023-09-13 01:04:42,845] [INFO] - hcg : HybridCommunicateGroup
[2023-09-13 01:04:42,845] [INFO] - mp_degree : 2
[2023-09-13 01:04:42,845] [INFO] - pp_degree : 1
[2023-09-13 01:04:42,845] [INFO] - pp_recompute_interval : 1
[2023-09-13 01:04:42,845] [INFO] - sharding :
[2023-09-13 01:04:42,845] [INFO] - broadcast_overlap : False
[2023-09-13 01:04:42,845] [INFO] - reduce_overlap : False
[2023-09-13 01:04:42,846] [INFO] - sharding_degree : 2
[2023-09-13 01:04:42,846] [INFO] - sharding_offload : False
[2023-09-13 01:04:42,846] [INFO] - sharding_stage : 3
[2023-09-13 01:04:42,846] [INFO] - Engine :
[2023-09-13 01:04:42,846] [INFO] - accumulate_steps : 1
[2023-09-13 01:04:42,846] [INFO] - eval_freq : 5000
[2023-09-13 01:04:42,846] [INFO] - eval_iters : 10
[2023-09-13 01:04:42,846] [INFO] - logging_freq : 1
[2023-09-13 01:04:42,846] [INFO] - max_steps : 10000
[2023-09-13 01:04:42,846] [INFO] - mix_precision :
[2023-09-13 01:04:42,846] [INFO] - custom_black_list : ['layer_norm', 'reduce_sum', 'c_softmax_with_cross_entropy', 'elementwise_div']
[2023-09-13 01:04:42,846] [INFO] - custom_white_list : ['lookup_table', 'lookup_table_v2']
[2023-09-13 01:04:42,846] [INFO] - dtype : float16
[2023-09-13 01:04:42,846] [INFO] - enable : True
[2023-09-13 01:04:42,846] [INFO] - level : O1
[2023-09-13 01:04:42,846] [INFO] - scale_loss : 65536.0
[2023-09-13 01:04:42,846] [INFO] - num_train_epochs : 1
[2023-09-13 01:04:42,846] [INFO] - save_load :
[2023-09-13 01:04:42,846] [INFO] - ckpt_dir : None
[2023-09-13 01:04:42,846] [INFO] - output_dir : ./output_mp
[2023-09-13 01:04:42,846] [INFO] - save_epoch : 1
[2023-09-13 01:04:42,846] [INFO] - save_steps : 1000
[2023-09-13 01:04:42,846] [INFO] - test_iters : 100
[2023-09-13 01:04:42,846] [INFO] - Global :
[2023-09-13 01:04:42,847] [INFO] - device : gpu
[2023-09-13 01:04:42,847] [INFO] - enable_partial_send_recv : True
[2023-09-13 01:04:42,847] [INFO] - global_batch_size : 8
[2023-09-13 01:04:42,847] [INFO] - local_batch_size : 4
[2023-09-13 01:04:42,847] [INFO] - micro_batch_size : 4
[2023-09-13 01:04:42,847] [INFO] - seed : 1024
[2023-09-13 01:04:42,847] [INFO] - Model :
[2023-09-13 01:04:42,847] [INFO] - attention_probs_dropout_prob : 0.0
[2023-09-13 01:04:42,847] [INFO] - ffn_hidden_size : 4096
[2023-09-13 01:04:42,847] [INFO] - fuse_attn_qkv : True
[2023-09-13 01:04:42,847] [INFO] - fused_linear : False
[2023-09-13 01:04:42,847] [INFO] - fused_softmax_with_triangular : False
[2023-09-13 01:04:42,847] [INFO] - hidden_dropout_prob : 0.0
[2023-09-13 01:04:42,847] [INFO] - hidden_size : 1024
[2023-09-13 01:04:42,847] [INFO] - initializer_range : 0.02
[2023-09-13 01:04:42,847] [INFO] - max_position_embeddings : 1024
[2023-09-13 01:04:42,847] [INFO] - module : GPTModule
[2023-09-13 01:04:42,847] [INFO] - name : GPT
[2023-09-13 01:04:42,847] [INFO] - no_recompute_layers : []
[2023-09-13 01:04:42,847] [INFO] - num_attention_heads : 16
[2023-09-13 01:04:42,847] [INFO] - num_layers : 24
[2023-09-13 01:04:42,847] [INFO] - recompute_granularity : full
[2023-09-13 01:04:42,847] [INFO] - scale_qk_by_layer_num : True
[2023-09-13 01:04:42,847] [INFO] - sequence_parallel : False
[2023-09-13 01:04:42,848] [INFO] - type_vocab_size : 16
[2023-09-13 01:04:42,848] [INFO] - use_flash_attn : False
[2023-09-13 01:04:42,848] [INFO] - use_recompute : True
[2023-09-13 01:04:42,848] [INFO] - vocab_size : 51200
[2023-09-13 01:04:42,848] [INFO] - vocab_size_divisible_unit : 128
[2023-09-13 01:04:42,848] [INFO] - Optimizer :
[2023-09-13 01:04:42,848] [INFO] - beta1 : 0.9
[2023-09-13 01:04:42,848] [INFO] - beta2 : 0.999
[2023-09-13 01:04:42,848] [INFO] - epsilon : 1e-08
[2023-09-13 01:04:42,848] [INFO] - grad_clip :
[2023-09-13 01:04:42,848] [INFO] - clip_norm : 1.0
[2023-09-13 01:04:42,848] [INFO] - name : ClipGradByGlobalNorm
[2023-09-13 01:04:42,848] [INFO] - lr :
[2023-09-13 01:04:42,848] [INFO] - decay_steps : 2880000
[2023-09-13 01:04:42,848] [INFO] - max_lr : 5e-05
[2023-09-13 01:04:42,848] [INFO] - min_lr : 1e-05
[2023-09-13 01:04:42,848] [INFO] - name : CosineAnnealingWithWarmupDecay
[2023-09-13 01:04:42,848] [INFO] - use_increments : True
[2023-09-13 01:04:42,848] [INFO] - warmup_rate : 0.01
[2023-09-13 01:04:42,848] [INFO] - multi_precision : True
[2023-09-13 01:04:42,848] [INFO] - name : FusedAdamW
[2023-09-13 01:04:42,848] [INFO] - tensor_fusion : False
[2023-09-13 01:04:42,848] [INFO] - weight_decay : 0.01
[2023-09-13 01:04:42,848] [INFO] - Profiler :
[2023-09-13 01:04:42,849] [INFO] - detailed : False
[2023-09-13 01:04:42,849] [INFO] - enable : False
[2023-09-13 01:04:42,849] [INFO] - profiler_log : profiler_log
[2023-09-13 01:04:42,849] [INFO] - scheduler : [1, 3]

源码：https://github.com/PaddlePaddle/PaddleFleetX/blob/develop/ppfleetx/core/engine/eager_engine.py
![image](https://github.com/PaddlePaddle/PaddleFleetX/assets/33216444/f076dc53-1699-439c-a222-449a877582cc)
以及parallel readme 策略支持说明图：
![image](https://github.com/PaddlePaddle/PaddleFleetX/assets/33216444/2a5bea43-6935-48ca-a072-3f7c650070ca)

套件源码check代码不让跑stage3 + mp，如果我修改该处，让gpt13b训练能够跑stage3 + mp请问这种做法可行吗？

**Comment by michaelowenliu** [comment]
你好，大模型推荐使用https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm
