### ISSUE TITLE
No module named 'ppfleetx'

### ISSUE THREAD

**Issue by Linzy19** [PaddlePaddle/PaddleFleetX#1108]
Traceback (most recent call last):
  File "/remote-home/lzy/Helixfold/helixfold/run_helixfold.py", line 37, in <module>
    from utils.init_env import init_seed, init_distributed_env
  File "/remote-home/lzy/Helixfold/helixfold/utils/init_env.py", line 19, in <module>
    from ppfleetx.distributed.protein_folding import dp
ModuleNotFoundError: No module named 'ppfleetx'
运行helixfold时候，按照gulide按照后，缺少ppfleetx，暂时没有找到合适的pip源来按照和下载。

**Comment by qfduli** [comment]
我也遇到这个问题了，请问解决了吗
